# Generated by Django 2.2.5 on 2019-09-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20190908_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('city', 'street', 'house', 'flat')},
        ),
    ]
